= LHPJavaMaterial

LHP Java 全栈开发课程课件补充材料。
Supplemental material for the Java full-stack development class.

Author: Samjna <snw201510@gmail.com>

== 功能 Functions
1. 课程大纲页面，附带课件下载链接。The table of contents of the class with the textbooks.
2. 课程词汇表。The glossary.

== 框架 Dependency
基于 https://vuejs.org/index.html[Vue.js^] 框架以及 https://element.eleme.io/[Element^] 组件库进行开发。

The project is based on https://vuejs.org/index.html[Vue.js^]
and https://element.eleme.io/[Element^], a component library of Vue.js.

== 许可证 License
https://github.com/snw2015/LHPJavaMaterial/blob/main/LICENSE[MIT 许可协议^]。许可证只针对本静态网站，不包含课件内容。

https://github.com/snw2015/LHPJavaMaterial/blob/main/LICENSE[MIT License^].
The license is only for the codes of the static website, excluding the textbooks on the site.

== 改动日志 Changelog
=== 1.0.0【2022/8/29】
* __New__ 实现基本功能。Core functions.

=== 1.1.0【2022/8/29】
* __New__ 导航栏响应式布局。Responsive design for the navigation bar.
* __New__ 搜索框自动补全。Autocomplete of the search box.
* __New__ 日文假名标注。The pronunciations of Japanese words in the glossary can be displayed.
* __Change__ 在移动端设备关闭惯性滚动。Momentum scrolling effect is now disabled for mobile devices.

=== 1.2.0【2022/8/30】
* __New__ 添加“回到顶部”按钮。A "backtop" button has been added.
* __New__ 现在按日文、英文或中文排序时将拆分对应语言的同义词为多个词条。
When sorted by a specific language, the synonyms of a word will be shown as separate entries.
* __Change__ 现在日文将按假名发音排序。Words is sorted by their pronunciation when sorted by Japanese.
* __Fix__ 修正英语单词内换行问题。Fixed the auto-wrap issue for English words.

=== 1.2.1【2022/8/30】
* __Minor__ 修正 UI 文本。Adjusted the text on UIs.

=== 1.2.2【2022/8/31】
* __Fix__ 修正按日文、英文或中文排序后再取消排序时的显示错误。
Fixed the wrong display of the glossary after canceling the sorting.

=== 1.2.3【2022/8/31】
* __Fix__ 再次尝试修正取消排序时的显示错误。
Another try to fixing the wrong display issue.

=== 1.3.0【2022/8/31】
* __New__ 增加课件页面的导航目录。Added the table of contents for the Classes page.
* __Change__ 添加了回到顶部按钮的响应式布局。Responsive design for the backtop button.
* __Minor__ 现在点击回到顶部按钮后会丢失焦点。Backtop button loses focus after clicked.

=== 1.3.1【2022/8/31】
* __Minor__ 增加指向官网的超链接。Add the hyperlink to the LHP homepage.

=== 1.3.2【2022/9/1】
* __Change__ 再次修改导航栏的响应式布局。Changed the responsive design for the navigation bar.
* __Fix__ 修正了导航栏图标。Fixed wrong behavior of the icons on the navigation bar.

=== 1.4.0【2022/9/4】
* __New__ 在地化（国际化）支持。I18n supported.
* __Change__ 数据文件结构做了若干调整以应对在地化。Adjusted the assets structure for i18n.
* __Fix__ 尝试修正导航栏高度。Try to fix the erroneous height of the navigation bar.

=== 1.4.1【2022/9/4】
* __Fix__ 修正了语言图标在移动端的显示问题。Fixed wrong behavior of the language selectoin icon on a mobile device.
* __Minor__ 暂时回调导航栏高度，之后再作进一步修正。Changed the height of the navigation bar again.

=== 1.4.2【2022/9/4】
* __Fix__ 修正了英文版导航栏的显示问题。Fixed the display errors of the navigation bar in English.

=== 1.4.3【2022/9/5】
* __Change__ 增加了日文课件的对应并调整了相关文件路径。Added the support for the Japanese textbooks.

=== 1.4.4【2022/9/5】
* __Minor__ 修正了多语言下的页面标题显示。Fixed the wrong page title diplayed when change the language.

=== 1.5.0【2022/9/5】
* __New__ 将教材页面目录放至边栏。The table of contents is now moved to a side menu view.
* __New__ 目录增加追踪高亮功能。The table of contents is now tracking the view position on the page.
* __Minor__ 微调了回到顶部按钮在移动端的位置。Adjusted the position of the backtop button on a mobile device.

=== 1.6.0【2022/9/6】
* __New__ 添加了单词表的导航功能。Added a navigation row for the glossary table.
* __Change__ 现在表头将和导航栏一起固定在顶部。The table header always sticks on top of the page.
* __Fix__ 修正了搜索框自动补全重复的问题。Fixed duplicated words shown in autocomplete.
* __Change__ 现在搜索框自动补全不区分大小写。Now the autocomplete is case-insensitive.
* __Minor__ 在搜索框添加清空按钮。Added a clear button in the search box.
* __Fix__ 修正了 UI 文本没有被翻译的问题。Fixed the untranslated UI text.

=== 1.6.1【2022/9/20】
* __Change__ 调整并对应了数据文件结构。The assets structure has been changed.
* __Minor__ 现在英文会以单词为单位自动补全。The autocomplete now show single English words rather than whole phrases.
